Add some dialogs in sponsors for feedbacks and advices
ogticrd/covid-safe-paths pull request #109
Opened 2020-06-29 19:50 UTC by JoseFcoEstrella

#### Description:
In this ticket have some changes:
- New sponsor is added
- A dialog in sponsors section is added (To inform the user about "why it takes long time to loading the sponsors")
- Another dialog for feedbacks when sponsors dont show something or take long time in loading

#### Linked issues:

[#166](https://trello.com/c/zKpiqAO3/166-actualizar-dos-url-en-auspiciadores)

#### Screenshots:

![Dialog in sponsors section](https://user-images.githubusercontent.com/51418416/86049275-dd6ecc80-ba1f-11ea-85d0-3a9ddf5941e4.PNG)

![new sponsor](https://user-images.githubusercontent.com/51418416/86049350-01321280-ba20-11ea-9b3b-8d61ed0c90ec.jpg)

#### How to test:

In app-->Go in settings--> sponsonsors and testing dialogs

2020-06-30 12:57 UTC, inteljudajocu requested changes
The changes in wording should be applied to other languages.

2020-06-30 12:57 UTC, inteljudajocu commented on app/locales/es.json
> +    "dialog_advice": "Algunos de los patrocinadores tardan un momento en cargar debido a la página de dicho patrocinador",
```suggestion
    "dialog_advice": "Algunos de los patrocinadores pueden tardan un momento en cargar debido a la página de dicho patrocinador",
```

2020-06-30 12:57 UTC, inteljudajocu commented on app/locales/es.json
> +    "dialog_error_advice": "Se produjo un error durante la carga. Por favor intente nuevamente más tarde.",
```suggestion
    "dialog_error_advice": "Se produjo un error durante la carga. Por favor inténtelo nuevamente más tarde.",
```

2020-06-30 12:57 UTC, inteljudajocu commented on app/views/DR/News/Details.js
> +              }, 15000),
Decrease timer to  10000

2020-06-30 14:37 UTC, inteljudajocu approved these changes

2020-06-30 15:28 UTC, D-Rosa99 commented
This peace of code appear in two places (***app/views/DR/Sponsors/index.js***, ***app/views/DR/News/Details.js***), and the only different is the text (the one with a red square), I think you can put this in a separate file and just call it wherever you want it to use

![image](https://user-images.githubusercontent.com/43874147/86144802-1e202180-bac4-11ea-8cb4-cedcdb68555d.png)

2020-06-30 16:07 UTC, RutsSantos approved these changes
LGTM

2020-06-30 18:38 UTC, Faustrox approved these changes
LGTM

2020-06-30 22:45 UTC, Faustrox approved these changes
LGTM

2020-07-01 14:05 UTC, D-Rosa99 approved these changes

2020-07-01 14:06 UTC, merged