Fix/48 check fonts guidelines
ogticrd/covid-safe-paths pull request #12
Opened 2020-05-15 14:15 UTC by D-Rosa99

#### Linked issues:

#### Screenshots:

#### How to test

2020-05-15 14:28 UTC, iocedano requested changes

2020-05-15 14:28 UTC, iocedano commented on android/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-6.3-all.zip
Please don't update the version now. we need to do more test!

2020-05-15 14:28 UTC, iocedano commented on app/constants/colors.js
> +  warningText: '#666804',
Let's be consistent with the naming convention.
Could you change those names to uppercase?

2020-05-15 14:28 UTC, iocedano commented on app/constants/colors.js
> +  tintColor,
Could we just use one variable for this?

2020-05-15 14:28 UTC, iocedano commented on app/constants/colors.js
> +  warningText: '#666804',
also, Could we named as the color name not base on what we use the color?
example:
```js
warningText: '#666804'
```
to 
```js
YUKON_GOLD: '#666804'
```

http://chir.ag/projects/name-that-color/

2020-05-15 16:15 UTC, RutsSantos reviewed
Left some comments

2020-05-15 16:15 UTC, RutsSantos commented on app/constants/themes.js
> +// import { Colors } from 'react-native/Libraries/NewAppScreen';
Remove comment

2020-05-15 16:15 UTC, RutsSantos commented on app/constants/themes.js
> +  background: Color.lightBlue,
"lightBlue" in Uppercase

2020-05-15 16:15 UTC, RutsSantos commented on app/views/onboarding/Onboarding1.js
> +import colors from '../../constants/colors';
Why do you have two imports of the same thing?

2020-05-17 18:56 UTC, adnanjt approved these changes
LGTM

2020-05-18 13:10 UTC, inteljudajocu reviewed
Left comments

2020-05-18 13:10 UTC, inteljudajocu commented on app/constants/colors.js
>    orange: '#ffc000',
change `orange` to `ORANGE`

2020-05-18 13:10 UTC, inteljudajocu commented on app/views/Import.js
> +  // buttonTouchable: {
Remove comments if unnecessary

2020-05-18 23:09 UTC, inteljudajocu approved these changes

2020-05-19 00:39 UTC, merged