Feat: Add webview in cards of dashboard
ogticrd/covid-safe-paths pull request #151
Opened 2020-08-07 19:53 UTC by JoseFcoEstrella

#### Description:
A link was added on the board, the same for each card, in which it directs you to a page with the cases of the covid of the country and its provinces
#### Linked issues:

[Ticket #252](https://trello.com/c/NonM37GZ/252-as-a-user-i-want-to-see-a-map-when-on-click-in-the-dashboard-cards-so-that-i-can-consult-the-cases-by-provinces-1)

#### Screenshots:
N/A
#### How to test:

In Home Screen all cards touch and redirect to the webview

2020-08-08 05:58 UTC, D-Rosa99 requested changes

2020-08-08 05:58 UTC, D-Rosa99 commented on app/views/DR/HomeScreen/index.js
> +      const url = 'https://coronavirusrd.gob.do/casos-de-covid-19-confirmados/';
I think this variable should have a better descriptive name, something like COVID_CASES_URL or CONFIRMED_COVID_CASES_URL
```suggestion
      const CONFIRMED_COVID_CASES_URL = 'https://coronavirusrd.gob.do/casos-de-covid-19-confirmados/';
```

2020-08-08 05:58 UTC, D-Rosa99 commented on app/views/DR/HomeScreen/index.js
> +                    </TouchableOpacity>
This piece of code its repeated 4 times in this file and its doing the same thing, just few things change, so you can create a component called Cards or DasboardCard and loop it up passing the parameters they need.
with the creation of the component you can remove getUrlMap function and just add that code to the onPress event.

create an array with the 4 elements or parameters of the card, and pass it to the code.

```
const dashboardCategories = [
      { label: 'label.positive_label', styles: '', value: confirmed },
      {
        label: 'label.deceased_label',
        styles: { color: Colors.BUTTON_LIGHT_TEX },
        value: deaths,
      },
      {
        label: 'label.recovered_label',
        styles: { color: Colors.GREEN },
        value: recovered,
      },
      {
        label: 'label.case_day_label',
        styles: { color: Colors.SUN },
        value: current,
      },
    ];

2020-08-08 06:02 UTC, D-Rosa99 commented
please take a screenshot of the map screen and add it to the description

2020-08-11 14:20 UTC, D-Rosa99 requested changes

2020-08-11 14:20 UTC, D-Rosa99 commented on app/views/DR/HomeScreen/index.js
> +        return (
You do not need this return, just delete it and remove `{}`
```suggestion
      return dashboardCategories.map(obj => 
         (
```

2020-08-11 14:20 UTC, D-Rosa99 commented on app/views/DR/HomeScreen/index.js
> +    const dashboardCards = () => {
I think it would be cleaner and better to read if you move this piece of code to other file

2020-08-11 14:20 UTC, D-Rosa99 requested changes

2020-08-11 14:20 UTC, D-Rosa99 commented on app/views/DR/HomeScreen/index.js
> +    };
I think it would be cleaner and better to read if you move this piece of code to other file

2020-08-12 13:15 UTC, D-Rosa99 requested changes

2020-08-12 13:15 UTC, D-Rosa99 commented on app/views/DR/HomeScreen/DashboardCards.js
> +export default function dashboardCards({
React Components must start with capital letter
```suggestion
export default function DashboardCards({
```

2020-08-12 13:24 UTC, D-Rosa99 commented on app/views/DR/HomeScreen/DashboardCards.js
> +      key={index}
Is not a best practice to use indexes as key in react list, you can use the label instead
```suggestion
      key={obj.label}
```

2020-08-12 19:28 UTC, D-Rosa99 approved these changes

2020-08-12 19:55 UTC, Faustrox approved these changes

2020-08-12 20:35 UTC, merged