Scroll epidemiologic screen
ogticrd/covid-safe-paths pull request #178
Opened 2020-09-09 14:39 UTC by RutsSantos

#### Description:
In smaller devices, the epidemiologicalScreen does not show correctly in terms of responsiveness

#### Linked issues:
[Ticket 238](https://trello.com/c/vzn9CS1F/238-add-scrollview-in-epidemiologicalstatus)

#### Screenshots:
![Simulator Screen Shot - iPhone 11 - 2020-09-09 at 10 33 11](https://user-images.githubusercontent.com/56127045/92612485-e8e43c80-f287-11ea-8fa8-82afb00a5682.png)

#### How to test:
`git fetch && git checkout scroll-epidemiologicScreen` then `yarn && cd ios && pod install`, after that run the project (if you can in a small device) and register as a positive user and see the responsiveness of the Epidemiological Discharge Screen.

2020-09-09 15:10 UTC, JoseFcoEstrella approved these changes

2020-09-09 15:16 UTC, D-Rosa99 requested changes
I've seen you have deleted some imports from MainApplication.java

import com.reactnativecommunity.androidprogressbar.RNCProgressBarPackage;	
import com.github.reactnativecommunity.location.RNLocationPackage;

Why??

One of them is to check the location from users, and the other is for something that happens in report screen.

Did you check that all of that is working correctly without those imports??

2020-09-10 13:21 UTC, RutsSantos commented
@D-Rosa99 as I explained you yesterday, no, the manual unlink of those libraries does not affect the general correct behavior of the app.

2020-09-10 15:08 UTC, D-Rosa99 requested changes
it's giving me an error because you've deleted the imports but no the implementation 

https://github.com/intellisysdcorp/covid-safe-paths/blob/7c7ff828d772bba1796ee49bce992e39318f798c/android/app/src/main/java/com/optic/covdr/MainApplication.java#L35

2020-09-10 16:25 UTC, D-Rosa99 approved these changes

2020-09-10 16:30 UTC, merged