Feat: Encrypting coordinates
ogticrd/covid-safe-paths pull request #181
Opened 2020-09-18 20:10 UTC by D-Rosa99

#### Description:

Encrypting users coordinates to make sure that they are transferring securely.
#### Linked issues:

Feat: [274](https://trello.com/c/khRffpOo/274-as-a-user-i-want-my-cordenades-send-encripted-so-that-i-can-be-sure-no-one-is-tracking-me-2)

#### How to test:

- `git pull && git checkout Feat/274-encypting-coordinates`
- Report yourself as positive covid user and change your location 
- The app should send your location encrypted 

**Note:** Talk to @epolanco to confirm that coordinates has been sent

2020-09-21 02:17 UTC, RutsSantos requested changes
Encryption should not be confused with encoding. Even though your code is right, it doesn't accomplish the motive of the ticket, that is to encrypt the location data. 

> Base64 encoded isn’t encryption on any level. It’s simply encodes text for transport and can easily be reversed.  You can easily encode and decode from the command line with the base64 command. No pass phrase or keys are needed. [Source](https://www.crossroadsinfosec.com/md5-base64-to-encrypt-passwords/#:~:text=Base64%20encoded%20isn't%20encryption,phrase%20or%20keys%20are%20needed.)

2020-09-21 14:21 UTC, D-Rosa99 commented
before to implement I talked to @epolanco about it, he said is just to try, if we see that all works correctly it will be change it

2020-09-21 18:40 UTC, RutsSantos approved these changes

2020-09-23 13:54 UTC, JoseFcoEstrella approved these changes

2020-10-01 17:59 UTC, merged