Continue report screen
ogticrd/covid-safe-paths pull request #22
Opened 2020-05-19 22:34 UTC by adnanjt

#### Description:

#### Linked issues:

#### Screenshots:

#### How to test:

2020-05-19 22:52 UTC, adnanjt commented
Current status
![image](https://user-images.githubusercontent.com/3283020/82386224-e07aa400-9a01-11ea-8bb7-ce31e0db0306.png)

2020-05-20 12:41 UTC, JoseFcoEstrella approved these changes
LGTM. Just need fix some line break

2020-05-20 12:41 UTC, JoseFcoEstrella commented on app/components/DR/CalendarButton/index.js
> +}
Without line break

2020-05-20 12:41 UTC, JoseFcoEstrella commented on app/components/DR/Input/index.js
> +}
WLB

2020-05-20 12:41 UTC, JoseFcoEstrella commented on app/components/DR/PhoneInput/index.js
> +}
WLB

2020-05-20 12:51 UTC, RutsSantos requested changes
LGTM. **But, solve conflicts.**
Also, i see React-native version is 0.62.2 when the MIT project is built in RN 0.61.5, wouldn't that make any trouble?

2020-05-20 15:54 UTC, adnanjt commented
> LGTM. **But, solve conflicts.**
> Also, i see React-native version is 0.62.2 when the MIT project is built in RN 0.61.5, wouldn't that make any trouble?

I can try fixing this today if I have time We should use the same one but not sure why updated

2020-05-20 18:22 UTC, inteljudajocu requested changes
images asset missing, the same asset as the other PR

2020-05-20 18:24 UTC, adnanjt commented
> images asset missing, the same asset as the other PR

This is gonna b fixed on the other one

2020-05-20 18:27 UTC, inteljudajocu approved these changes

2020-05-20 18:50 UTC, merged