Fix: changing text language
ogticrd/covid-safe-paths pull request #29
Opened 2020-05-21 05:26 UTC by D-Rosa99

#### Description:

I changed the language in some of the screen, except the report symptoms screen and fom
#### Linked issues:

[#58](https://trello.com/c/GKx94lfy/58-revisar-el-idioma-del-app)
#### Screenshots:

#### How to test:

2020-05-21 11:18 UTC, JoseFcoEstrella approved these changes
LGTM

2020-05-21 13:55 UTC, iocedano approved these changes

2020-05-21 13:56 UTC, iocedano requested changes
Please update the snapshots

2020-05-22 01:17 UTC, inteljudajocu approved these changes
LGTM

2020-05-22 01:27 UTC, merged