Added language translations of the answers form
ogticrd/covid-safe-paths pull request #75
Opened 2020-06-10 14:44 UTC by JoseFcoEstrella

#### Description:
Added English translations of the answers form and fix a grammar problem
#### Linked issues:

[#143](https://trello.com/c/5KTJDCqc/143-traducir-al-inglés-los-grupos-de-respuesta-del-formulario) and [#141](https://trello.com/c/s0rtoCdO/141-fix-de-wording-en-respuestas)
#### Screenshots:

![Captura](https://user-images.githubusercontent.com/51418416/84283343-e0555c00-ab08-11ea-8068-cebb1a405c5a.PNG)
 
![WhatsApp_Image_2020-06-06_at_2 31 15_PM jpeg](https://user-images.githubusercontent.com/51418416/84283455-024ede80-ab09-11ea-85db-de92e02b58dc.jpg)

#### How to test:

2020-06-10 19:00 UTC, inteljudajocu commented on app/locales/en.json
> +          "title": "Always remember to “wash your hands with soap and water frequently and apply social distancing”",
Maybe like this:
```suggestion
          "title": "Always remember to “wash your hands with soap and water frequently and practice social distancing”",
```

2020-06-10 19:00 UTC, inteljudajocu commented on app/locales/en.json
> +        "none": "According to his answers, he should stay at home and away from others. If you can, ten a room and a bathroom that are just for you. This can be difficult when you are not feeling wel
```suggestion
        "none": "According to his answers, he should stay at home and away from others. If you can, have a room and a bathroom that are just for you. This can be difficult when you are not feeling well, but it will protect those around you.",
```

2020-06-10 19:00 UTC, inteljudajocu commented on app/locales/en.json
> +          "content": "Your answers may be possible to discuss the COVID - 19 test. You should contact your doctor, or contact the Aurora platform at 809-449-6262, 809 409 6262 and 809-352-6262 or cal
```suggestion
          "content": "Your answers may be possible to discuss the COVID - 19 test. You should contact your doctor, or contact the Aurora platform at 809-449-6262, 809 409 6262 and 809-352-6262 or call *462 for more information. Trial access may vary by location and provider. Check the laboratories that are authorized by the Ministry of Public Health available in your province of residence."
```

2020-06-10 19:32 UTC, D-Rosa99 approved these changes

2020-06-10 20:09 UTC, inteljudajocu approved these changes

2020-06-10 21:11 UTC, D-Rosa99 approved these changes

2020-06-10 21:12 UTC, RutsSantos requested changes
What you have so far LGTM, but you need to translate it to more languages, not just English. You can see the _locales_ folder to see the others languages you need to translate it to.

2020-06-15 21:29 UTC, Faustrox approved these changes
LGTM

2020-06-15 22:03 UTC, adnanjt commented
![Screenshot_20200615-175941](https://user-images.githubusercontent.com/3283020/84710535-68d16380-af32-11ea-93bb-e6f349a28b3a.png)
Pk se ve ese titulo con Underscore _ en tu PR ?
@JoseFcoEstrella

2020-06-16 15:11 UTC, RutsSantos approved these changes
LGTM

2020-06-16 15:32 UTC, merged