Add spanish to privacy policy
ogticrd/covid-safe-paths pull request #94
Opened 2020-06-17 20:02 UTC by JoseFcoEstrella

#### Description:
Add spanish to privacy policy
#### Linked issues:
[#Tick157](https://trello.com/c/bN7AB60N/157-incluir-politicas-de-privacidad-en-español)
#### Screenshots:

[Docs of the privacy policy in spanish](https://docs.google.com/document/d/1znFbxn02pqVFFR9EDQh7jc28qBjWWI-MH7G50EFxEgs/edit)

#### How to test:
In the app into settings-> legal -> privacy policy

2020-06-17 20:11 UTC, D-Rosa99 requested changes

2020-06-17 20:11 UTC, D-Rosa99 commented on app/views/Licenses.js
> +      i18n.language === 'es' ? PRIVACY_POLICY_URL_ES : PRIVACY_POLICY_URL,
You are using this line of code twice in this file, I think is better create a variable with the two option and use it where its need

2020-06-17 21:07 UTC, D-Rosa99 approved these changes

2020-06-18 12:52 UTC, inteljudajocu approved these changes
LGTM

2020-06-18 14:44 UTC, merged